VehicleServiceManagement/Controllers/VehicleController.cs
/*********************************************************************************************************** * Created by       : Albin Anto * Created On       : 20th Oct 2021 *  * Reviewed By      : Hilda sister * Reviewed On      : 26th Nov 2021 *  ***********************************************************************************************************/
namespace VehicleServiceManagement.Controllers
{
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Net;
    using System.Net.Mail;
    using VehicleServiceManagement.Data;
    using VehicleServiceManagement.Models;
    using VehicleSeviceManagement.Framework;
    using VehicleSeviceManagement.Framework.Helper;
    public class VehicleController : Controller
    {

        //Injecting a Vehicle repository
        private readonly IVehicleRepository _vehicleRepository;
        /// <summary>
        /// Constructor of Vehicle repository
        /// </summary>
        /// <param name="_vehicleRepository"></param>
        public VehicleController(IVehicleRepository _vehicleRepository)
        {
            this._vehicleRepository = _vehicleRepository;
        }
        // Creating an object for Comman model
        CustomerCommanModel customerCommanModel = new CustomerCommanModel();
        #region Show Registertion
        /// <summary>
        /// To show registerion page
        /// </summary>
        /// <returns></returns>
        public IActionResult Registertion()
        {
            return View();
        }
        #endregion
        #region Index Page
        /// <summary>
        /// To show an index page
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            DataValue dv = new DataValue();
            customerCommanModel = _vehicleRepository.FetchCustomerCount(dv);
            customerCommanModel = _vehicleRepository.FetchGst(dv);
            if (customerCommanModel.GstList != null && customerCommanModel.GstList.Count > 0)
            {
                HttpContext.Session.SetString(MessageCatalog.Customer.CustomerProperty.ABOVETHOUSAND, customerCommanModel.GstList[0].AboveThousand.ToString());
                HttpContext.Session.SetString(MessageCatalog.Customer.CustomerProperty.LESSTHOUSAND, customerCommanModel.GstList[0].LessThousand.ToString());
            }
            return View(customerCommanModel);
        }
        #endregion
        #region Check Login 
        /// <summary>
        /// Check username and password if its corrext allow to index page  else stay in Registertion page
        /// </summary>
        /// <param name="customer">By this parameter can get its properties</param>
        /// <returns></returns>
        public IActionResult CheckLogin(CustomerModel customer)
        {
            try
            {
                HttpContext.Session.Clear();
                if (!string.IsNullOrEmpty(customer.Email) && !string.IsNullOrEmpty(customer.Password))
                {
                    CustomerCommanModel customerCommanModel = new CustomerCommanModel();
                    DataValue dv = new DataValue();
                    dv.Add(MessageCatalog.Customer.CustomerProperty.EMAIL, customer.Email, EnumCommand.DataType.Varchar);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.PASSWORD, customer.Password, EnumCommand.DataType.nVarchar);
                    customerCommanModel = _vehicleRepository.CheckUserName(dv);
                    if(customerCommanModel.customermodelList != null && customerCommanModel.customermodelList.Count > 0)
                    {
                        HttpContext.Session.SetInt32(MessageCatalog.Customer.CustomerProperty.USERROLL, customerCommanModel.customermodelList[0].UserRoll);
                        HttpContext.Session.SetInt32(MessageCatalog.Customer.CustomerProperty.CUSTOMERID, customerCommanModel.customermodelList[0].CustomerId);
                        HttpContext.Session.SetString(MessageCatalog.Customer.CustomerProperty.CUSTOMERNAME, customerCommanModel.customermodelList[0].CustomerName);

                        TempData[MessageCatalog.ToastrTypes.ToastrMessage] = string.Format(MessageCatalog.ToastrStyle.Toastr_Style, MessageCatalog.ToastrTypes.Success, "Username And Password is correct!", MessageCatalog.ToastrTypes.Success);

                        return RedirectToAction("Index", customerCommanModel);
                    }
                    else if(customerCommanModel.customermodelList == null)
                        TempData[MessageCatalog.ToastrTypes.ToastrMessage] = string.Format(MessageCatalog.ToastrStyle.Toastr_Style, MessageCatalog.ToastrTypes.Error, "Invalid username or password!", MessageCatalog.ToastrTypes.Error);
                }

            }
            catch (Exception ex)
            {
                new ErrorLog().WriteLog(ex);
            }
            return View("Registertion");
        }
        #endregion
        #region Save Registertion Customer Details
        /// <summary>
        ///  Insert an customer Registertion records  into db
        /// </summary>
        /// <param name="customer"> Creating a object for customermodel so that we can access its property</param>
        /// <returns></returns>
        public IActionResult SaveCustomer(CustomerModel customer)
        {
            try
            {
                if (!string.IsNullOrEmpty(customer.CustomerId.ToString()) && !string.IsNullOrEmpty(customer.CustomerName)
                && !string.IsNullOrEmpty(customer.Email) && !string.IsNullOrEmpty(customer.MobileNo) && !string.IsNullOrEmpty(customer.Address)
                && !string.IsNullOrEmpty(customer.Password))
                {
                    ResultArgs result = new ResultArgs();
                    DataValue dv = new DataValue();
                    dv.Add(MessageCatalog.Customer.CustomerProperty.CUSTOMERID, customer.CustomerId, EnumCommand.DataType.Int);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.CUSTOMERNAME, customer.CustomerName, EnumCommand.DataType.Varchar);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.EMAIL, customer.Email, EnumCommand.DataType.Varchar);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.MOBILENO, customer.MobileNo, EnumCommand.DataType.Varchar);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.ADDRESS, customer.Address, EnumCommand.DataType.Varchar);
                    dv.Add(MessageCatalog.Customer.CustomerProperty.PASSWORD, customer.Password, EnumCommand.DataType.nVarchar);
                    result = _vehicleRepository.InsertCutomerRegistertion(dv);
                    if (ConversionHelper.ToInt32(result.ReturnValue) == -1)
                        TempData["ToastrMessage"] = string.Format(MessageCatalog.ToastrStyle.Toastr_Style, MessageCatalog.ToastrTypes.Error, "Customer Details not Save!", "error");
                    else if (ConversionHelper.ToInt32(result.ReturnValue) == 1)
                        TempData["ToastrMessage"] = string.Format(MessageCatalog.ToastrStyle.Toastr_Style, MessageCatalog.ToastrTypes.Success, "Customer Details Saved!", "success");
                }
                else
                    TempData["ToastrMessage"] = string.Format(MessageCatalog.ToastrStyle.Toastr_Style, MessageCatalog.ToastrTypes.Error, "Customer details not saved because value is empty!", "error");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View("Registertion");
        }
        #endregion
        #region Change password using otp
        /// <summary>
        /// To show forget password page
        /// </summary>
        /// <returns></returns>
        public IActionResult Forgetpassword()
        {
            return View();
        }
        /// <summary>
        /// To check the email id and sent otp to customer
        /// </summary>
        /// <param name="customer">By parameter get an email id</param>
        /// <returns></returns>
        public IActionResult EmailCheck(CustomerModel customer)
        {
            var RandomCode = new Random();
            try
            {
                string emailFromAddress = Settingsconfiguration.Configuration?.SMTPMailConfig?.emailFromAddress.ToString();
                string subject = Settingsconfiguration.Configuration?.SMTPMailConfig?.subject.ToString();
                string SMTPServer = Settingsconfiguration.Configuration?.SMTPMailConfig?.SMTPServer.ToString();
                int SMTPPort = Convert.ToInt32(Settingsconfiguration.Configuration?.SMTPMailConfig?.SMTPPort.ToString());
                string password = Settingsconfiguration.Configuration?.SMTPMailConfig?.password.ToString();
                bool enableSSL = ConversionHelper.ToBoolean(Settingsconfiguration.Configuration?.SMTPMailConfig?.enableSSL);
                string body = Settingsconfiguration.Configuration?.SMTPMailConfig?.body.ToString();
                var otp = RandomCode.Next(0, 999999).ToString("D6");
                HttpContext.Session.SetString(MessageCatalog.Customer.CustomerProperty.OTP, otp);
                HttpContext.Session.SetString(MessageCatalog.Customer.CustomerProperty.EMAIL, customer.Email);
                MailMessage mail = new MailMessage();

                mail.From = new MailAddress(emailFromAddress);
                mail.To.Add(customer.Email);
                mail.Subject = subject;
                mail.Body = body + otp;
                mail.IsBodyHtml = true;
                //mail.Attachments.Add(new Attachment("D:\\TestFile.txt"));//--Uncomment this to send any attachment
                using (SmtpClient smtp = new SmtpClient(SMTPServer, SMTPPort))
                {

VehicleServiceManagement/Views/Vehicle/Changepassword.cshtml
@{
    Layout = null;
}

@model VehicleServiceManagement.Models.CustomerCommanModel

 <link href="~/Images/Logo/vehicle.png" rel="icon">
<link href="~/css/Registertionbootstrap.min.css" rel="stylesheet" />
<script src="~/css/Registertionbootstrap.min.js"></script>
<script src="~/css/jquery-1.11.1.min.js"></script>
<link href="~/css/Mycss.css" rel="stylesheet" />
<script src="~/js/site.js"></script>
<style>
    input.error {
        border: 1px solid red;
        color: red;
    }

    label.error {
        font-weight: bold;
        color: red;
    }

    .redcolor {
        color: red;
    }

    .Greencolor {
        color: green;
    }
    .login {
        background: url('./images/login-new.jpeg')
    }
</style>
<partial name="_CommanShared" />
<!------ Include the above in your HEAD tag ---------->
<body class="h-screen font-sans login bg-cover"></body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6 text-center">
                            <a style="color:green">Forget Password</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form-OTP" method="post" asp-controller="Vehicle" asp-action="Changepass" role="form" style="display: block;">
                                <div class="form-group">
                                    <input tabindex="1" type="password" name="password" class="form-control" placeholder="password" id="txtPassword" asp-for="customerModel.Password" required minlength="8" maxlength="50">
                                </div>
                                <div class="form-group">
                                    <input tabindex="2" type="password" name="confirm password" class="form-control" id="txtConfirmPassword" placeholder="confirm password" required minlength="8" maxlength="50">
                                </div>
                                <div class="registrationFormAlert" id="CheckPasswordMatch">
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 col-sm-offset-3">
                                        <input type="submit" tabindex="3" class="form-control btn btn-login" value="Submit">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="lastDiv"></div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
@*To use Jquery*@
<script src="~/js/jquery.min.js"></script>
<!-- For jquery validation plugin -->
<script src="~/plugins/JqueryValidation/jquery-1.11.1.min.js"></script>
<script src="~/plugins/JqueryValidation/jquery.validate.min.js"></script>
<script src="~/plugins/JqueryValidation/additional-methods.min.js"></script>
<script>
    $(document).ready(function () {

        $("#lastDiv").nextAll("center").remove();

        setTimeout(function () {

            $("#lastDiv").nextAll("div").remove();

        }, 400);

        setTimeout(function () {

            $("#lastDiv").nextAll("div").remove();

        }, 500);

    });
</script>
<script>
    $(document).ready(function () {
        //To check password and confirmpassword
        $("#txtConfirmPassword").keyup(checkPasswordMatch);
    });
</script>
<script>
    //To check password and confirmpassword
    function checkPasswordMatch() {
        $("#CheckPasswordMatch").text("");
        $("#CheckPasswordMatch").removeClass("redcolor")
        $("#CheckPasswordMatch").removeClass("Greencolor")

        var password = $("#txtPassword").val();
        var confirmPassword = $("#txtconfirmpassword").val();

        if (password == "" || confirmPassword == "") {
            $("#CheckPasswordMatch").text("");

        }
        else if (password != confirmPassword) {
            $("#CheckPasswordMatch").text("Passwords does not match!").addClass("redcolor");
        }
        else
            $("#CheckPasswordMatch").text("Passwords match.").addClass("Greencolor");
    }
    //Jquery validation
    jQuery.validator.setDefaults({
        debug: true,
        success: "valid"
    });
    //To email
    $("#login-form-OTP").validate({
        password: {
            required: true,
            email: true,
            maxlength: 50
        },
        txtConfirmPassword: {
            required: true,
            email: true,
            maxlength: 50
        },
        //By this submit handler only we can able to use submit and button
        submitHandler: function (form) {
            form.submit();
        }
    });
</script>

VehicleServiceManagement/Views/Vehicle/CustomerReport.cshtml
@model CustomerCommanModel
<!--Grid Form-->
<style>
    .loader {
        position: fixed;
        left: 50%;
        top: 50%;
        background-color: none;
    }

    #holder > li {
        padding: 5px;
        margin: 2px;
        display: inline-block;
    }

        #holder > li[data-page] {
            border: solid #a0a0a0 1px;
            border-radius: 5px;
        }

        #holder > li.separator:before {
            content: '...';
        }

        #holder > li.active {
            background-color: darkgrey;
            color: #fff;
        }

        #holder > li[data-page]:hover {
            cursor: pointer;
        }


</style>
<div class="">
    <div class="loader">
        <img src="~/Images/loader.gif" width="50" />
    </div>
</div>
<div class="flex flex-1  flex-col md:flex-row lg:flex-row mx-2 mb-6">
    <div class="mb-2 border-solid border-gray-300 rounded border shadow-sm w-full">
        <div class="bg-gray-500 px-2 py-3 border-solid border-gray-400 border-b mt-4 text-center" style="color:white;font-size:30px">
            CUSTOMER DETAILS REPORT
        </div>
        <br />
        <div class="col-md-12 text-left mt-3">
            <label class="font-weight-bold">Show</label>
            <select id="entries" @*class="border-2 badge-dark"*@ style="border:1px solid #aaa;border-radius: 3px;padding: 4px;" onchange="entrieschange();">
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
            <label class="font-weight-bold">entries</label>
            <div class="text-right">
                <label>Search:</label>
                <input type="text" id="myInput" style="border:1px solid #aaa;border-radius: 3px;padding: 4px;">
            </div>
        </div>

        <div class="container " id="ExportHtml">
            <table class="table-striped table-bordered nowrap table-hover table-responsive-lg mytable" style="width:99.9% ;cursor:not-allowed;" id="mysort">
                <thead class="bg-grey-dark text-white text-normal">
                    <tr>
                        <th class="border w-1/6 px-4 py-2">CustomerName</th>
                        <th class="border w-1/6 px-4 py-2">Email</th>
                        <th class="border w-1/6 px-4 py-2">MobileNo</th>
                        <th class="border w-1/6 px-4 py-2">Address</th>
                    </tr>
                </thead>
                <tbody>
                    <div class="row noprint text-right">
                        <div class="col-md-6 float-right noprint">
                            <a onclick=" printScrollingDiv()" title="Print"><i class="fa fa-print"></i>Print</a>
                            <a asp-area="Report" asp-controller="Report" asp-action="Export" onclick="ExportData(2,'Report');" title="Export To Excel" style="color:green"><i class="fa fa-file-excel"></i>Excel</a>
                            <a asp-area="Report" asp-controller="Report" asp-action="Export" onclick="ExportData(1,'Report');" title="Export To Word" style="color:blue"><i class="fa fa-file-word"></i>Word</a>
                        </div>
                    </div>
                    <tr></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-md-6 text-left show mt-3">
    </div>
    <div class="col-md-6
                 mt-3 text-right">
        <div id="holder"></div>
    </div>
</div>
<div id="export-content">
</div>
<!--Grid Form-->
<script src="~/js/jquery.min.js"></script>
<script src="~/js/Page.js"></script>
<script>
    //This is for sorting by plugin
    $(document).ready(function () {
        //To use search icon
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#mysort tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
    //To use loader
$(window).load(function () {
        $(".loader").fadeOut("slow");
    });
    function FetchCustomerDetails() {
        Entries = $('#entries').val();
       $.ajax({
            type: 'POST',
             url:'@Url.Action("FetchCustomerDetails", "Vehicle")',
            dataType: 'json',
           cache: false,
           data: { Entries: Entries, Pages: Pages, OffsetRows: OffsetRows},
            success: function (result) {
               console.log(result);
                if (result != null) {
                    Count = result.count;
                    $('#mysort tbody tr').remove();
                    $('.nodata').remove();
                    if (result.customermodelList!= null) {
                        for (var i = 0; i < result.customermodelList.length; i++) {
                            var rows = '';
                            rows += "<tr>";
                            rows += "<td>" + result.customermodelList[i].customerName + "</td>";
                            rows += "<td>" + result.customermodelList[i].email + "</td>";
                            rows += "<td>" + result.customermodelList[i].mobileNo + "</td>";
                            rows += "<td>" + result.customermodelList[i].address+ "</td>";
                            rows += "</tr>";
                            $('#mysort tbody').append(rows);
                        }
                        pagelooping();
                    }
                    else {
                        var nodata = "<label class='font-weight-bold nodata'>No data found</label>"
                        $('#mysort tbody').append(nodata);

                    }
                }
            }
        });
    }
    //This is for exporting excel,wordm, print
    function printScrollingDiv(divName, paging) {
        if (!paging) {
            paging = 0;
        }
        if (paging != 0) {
            var table = $('.table').DataTable();
            var pagelength = table.page.len();
            table.page.len(-1).draw();
        }
        $("#export-content").html($("#ExportHtml").html());
        $("#export-content").find(".dataTables_filter").remove();
        $("#export-content").find(".dataTables_info").remove();
        $("#export-content").find(".dataTables_length").remove();
        $("#export-content").find(".dataTables_paginate").remove();
        $("#export-content").find(".noprint").remove();
        var header = "<html> <head><style> table { font-size:8pt !important; width: auto  !important; overflow: hidden !important;} " +
            " body{  font-family: Verdana, Arial, Helvetica, sans-serif; color: #000000; font-style: normal; }" +
            " p{ font-size: 8pt; } label{ font-size: 8pt; }" +
            " .pagecaption 	{ font-weight: bold; font-size: 16pt; }" +
            " h4	{ margin-bottom:2px  !important;font-size: 12pt;} h5,h6{ margin:5px 0 5px  !important;  font-size: 10pt; font-weight:bold !important;} h6	{ font-weight: normal; font-size: 10pt   !important; }" +
            " table			{ border-top: gray 1px solid; border-left: gray 1px solid; font-size:8pt;border-collapse: collapse;width:auto !important;min-width:50% !importnat}" +
            "  table td		{ border-right: gray 1px solid; border-bottom: gray 1px solid; padding: 3px;border-collapse: collapse;}" +
            " table th		{ border-right: gray 1px solid; border-bottom: gray 1px solid; padding: 3px; font: bold; background-color: #CCCCCC; text-align: left;border-collapse: collapse;margin:0 !important; }" +
            "a{text-decoration: none;pointer-events:none;color:#000;}.dataTables_empty{text-align:center}" +
            "h5 {font-weight: 700 !important;font-size: 9pt!important;}" +
            "h6 {font-weight: normal!important;font-size: 9pt!important;}" +
            "</style>  <title>Vehicle Service Management</title></head><body>";
        var footer = "</body></html>";
        var export_data = header + $("#export-content").html() + footer;
        $("#export-content").html('');
        var w = window.open();
        var html = export_data;
        $(w.document.body).html(html);
        if (paging != 0) {
            table.page.len(pagelength).draw();
        }
    }
    function ExportData(export_type, file_name, paging = 0) {
        if (paging != 0) {
            var table = $('.mytable').DataTable();
            var pagelength = table.page.len();
            table.page.len(-1).draw();
        }
        $("#export-content").html($("#ExportHtml").html());
        $("#export-content").find(".noprint").remove();
        $("#export-content").find(".dataTables_filter").remove();
        $("#export-content").find(".dataTables_info").remove();
        $("#export-content").find(".dataTables_length").remove();
        $("#export-content").find(".dataTables_paginate").remove();
        var header = "<html> <head><style> table { font-size:9pt; } " +
            " body{  font-family: Verdana, Arial, Helvetica, sans-serif; color: #000000; font-style: normal; }" +
            " p{ font-size: 8pt; } label{ font-size: 8pt; }" +
            " .pagecaption 	{ font-weight: bold; font-size: 16pt; }" +

            "  h4	{ margin-bottom:2px  !important;font-size: 12pt;} h5,h6{ margin:5px 0 5px  !important;  font-size: 10pt;} h6	{ font-weight: bold; font-size: 10pt   !important; }" +
            " table			{ border-top: gray 1px solid; border-left: gray 1px solid; font-size:8pt;border-collapse:collapse}" + ".table_positionset{ margin-top:10px !important;}" +
            "  table td		{ border-right: gray 1px solid; border-bottom: gray 1px solid; padding: 3px;}" +
            " table th		{ border-right: gray 1px solid; border-bottom: gray 1px solid; padding: 3px; font: bold; background-color: #CCCCCC; text-align: left; }" +
            ".dataTables_scrollBody table thead {display:none !important}" +
            "a{text-decoration: none;pointer-events:none;color:#000;}.dataTables_empty{text-align:center}" +

            "h5 {font-weight: normal!important;font-size: 9pt!important;}" +
            "h6 {font-weight: normal!important;font-size: 9pt!important;}" +
            "</style>  <title>Option C</title></head><body>";
        var footer = "</body></html>";
        var export_data = header + $("#export-content").html() + footer;
        $("#export-content").html('');

        // This will be called when the action clicked
        $.ajax({
            url:'@Url.Action("SetExportOptions","Report", new { area = "Report" })',
            data: { exportHtml: export_data, exportType: export_type, fileName: file_name },
            cache: false,
            async: false,
            type: "POST",
            success: function (data) {
            },
            error: function (reponse) {

            }
        });

        if (paging != 0) {
            table.page.len(pagelength).draw();
        }
    }
</script>